---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(reticulate)
library(tidyverse)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

course_dataset = pd.read_csv("Data/Data - DS C1 Course.csv")



course_dataset.info()
course_dataset.summarize()
course_dataset.describe()
print(course_dataset.isnull().values.sum())

```
```{python}
course_dataset["Do you understand that this is a paid course ?"] = course_dataset["Do you understand that this is a paid course ?"].replace(np.nan, "none" )
course_dataset["Course Fee Email"] = course_dataset["Course Fee Email"].replace(np.nan, "Not Sent")
course_dataset["Date sent"] = course_dataset["Date sent"].replace(np.nan, "-")
course_dataset["Payment"] = course_dataset["Payment"].replace(np.nan, "Not paid")
course_dataset["Payment Receipt Sent"] = course_dataset["Payment Receipt Sent"].replace(np.nan, "not yet")
course_dataset["Do you have any feedback, thoughts, or comments you would like to share?"] = course_dataset["Do you have any feedback, thoughts, or comments you would like to share?"].replace(np.nan, "None")
course_dataset["Do you have a LinkedIn Account?"] = course_dataset["Do you have a LinkedIn Account?"].replace(np.nan, "not stated")
course_dataset["Which Country are you currently residing in?"] = course_dataset["Which Country are you currently residing in?"].replace(np.nan, "not stated")  
course_dataset["Which City are you currently residing in?"] = course_dataset["Which City are you currently residing in?"].replace(np.nan, "not stated")
```


```{r}

dataRenamed <- course_dataset %>%
  rename("Id" = "Student.ID",
         "Date_time" = "Timestamp",
         "Qr_uni_col" = "Name.of.University.or.College.currently.or.previously.attended."
  )

# Check for renaming
names(dataRenamed[1:10])

dataSelected <- select(dataRenamed,
                       Id, Date_time, Qr_uni_col)

# make ID rowname of data frame
dataSelected <- column_to_rownames(dataSelected , var = "Id")

head(dataSelected)


dataCategorized <- dataSelected %>%
  mutate(
    Uni_col = case_when(
      str_detect(
        Qr_uni_col,
        "IBA|Institute of Business Administration|Iba Karachi|IBA, Karachi|Iba Karachi|institute of business administration|Institute of business administration|INSTITUTE OF BUSINESS ADMINISTRATION KARACHI|Institute Of Business Administration|Institute Of Business Administration, Karachi|Institute of Business Adminstration|Institute of business administration karachi|INSTITUTE OF BUISNESS ADMINISTRATION KARACHI"
      ) ~ "IBA",
      str_detect(
        Qr_uni_col,
        "Azam|Quaid I azam university|Quaid-I-Azam University, Islamabad|Quaid e Azam University|Quaid e Azam university       Islamabad|Quaid-e-Azam University Islamabad|Quaid-i-Azam University Islamabad|Quaid e Azzam university Islamabad"
      ) ~ "QU",
      str_detect(
        Qr_uni_col,
        "Sir syed university of Engineering Technology|Sir syed university of engineering and technology|Sir Syed University|Sir Syed University Of Engineering And Technology|Sir Syed University Of Engineering & Technology|Sir syed University of engineering and technology|Sirsyed university of engineering and technology|Sir Syed University of Engineering and Technology|Sir Syed university of engineering and technology|Sur Syed University of Engineering and Technology|Sir Syed University Engineering Technology"
      ) ~ "SYED",
      str_detect(
        Qr_uni_col,
        "Ned university|NED University of Engineering and Technology Karachi|NED|Ned University"
      ) ~ "NED",
      str_detect(Qr_uni_col, "IQRA|Iqra|iqra|iqra university") ~ "IQRA",
      str_detect(Qr_uni_col, "Sindh") ~ "SMIU" ,
      str_detect(Qr_uni_col, "Karachi|University of karachi") ~ "KU",
      str_detect(Qr_uni_col, "Szabist", ) ~ "SZABIST",
      str_detect(Qr_uni_col, "Management|management", ) ~ "IOBM",
      str_detect(Qr_uni_col, "University of engineering and technology Peshawar") ~ "UET",
      TRUE ~ Qr_uni_col  #keep all others same
    )
  )




```


Column {data-width=350}
-----------------------------------------------------------------------
```{python}

data_by_category = r.dataCategorized
uni_frequency = data_by_category["Uni_col"].value_counts()


```

### Chart B

```{python}
import pandas as pd
import numpy as np
from datetime import datetime

cleaned_data = course_dataset.join(r.dataCategorized)
cleaned_data.to_csv("ds_course.csv")
```


```{python}
import seaborn as sns

```


### Chart C

```{r}

```

